# Install Phase: Installs dependencies and sets up the environment.
# Pre-Build Phase: Prepares the environment for the build process.
# Build Phase: Focuses on building the application and creating artifacts.
# Artifacts: Specifies the files to be included in the output artifacts.
# Cache: Specifies paths to be cached for faster builds.
# Added yum command for Amazon Linux
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y wget unzip fontconfig freetype-devel fontconfig-devel
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest-html
      - pip install playwright
      - echo "Verifying playwright installation..."
      - playwright --version
      - echo "Setting up playwright browsers..."
      - export PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright
      - mkdir -p $PLAYWRIGHT_BROWSERS_PATH
      - python -m playwright install chromium
      - echo "Playwright dependencies installed."

  pre_build:
    commands:
      - echo "Preparing for build..."
      - mkdir -p artifacts

  build:
    commands:
      - echo "Building the application..."
      - # Add build commands here, such as creating artifacts
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/root/.cache/ms-playwright/**/*'