# AWS CodeBuild buildspec.yml will run test stage as configured in post-build
# NOT to run test stage in buildspec.yml file and then:
# remove "post_build"
# artifacts remove path and add - '**/*'
# added yum command for Amazon Linux

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y wget unzip fontconfig freetype-devel fontconfig-devel
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest-html
      - pip install playwright
      - echo "Verifying playwright installation..."
      - playwright --version
      - echo "Setting up playwright browsers..."
      - export PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright
      - mkdir -p $PLAYWRIGHT_BROWSERS_PATH
      - python -m playwright install chromium
      - echo "Playwright dependencies installed."

  pre_build:
    commands:
      - echo "Preparing for tests..."
      - export HEADLESS=true
      - mkdir -p artifacts

  build:
    commands:
      - echo "Running tests..."
      - pytest -s -v tests/test_parameter_apple_search_module.py --html=report_playwright_bdd.html --maxfail=3 --disable-warnings -v
      - cp report_playwright_bdd.html artifacts/

artifacts:
  files:
    - artifacts/report_playwright_bdd.html
    - screenshots/**/*
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'